return {
  "pmizio/typescript-tools.nvim",
  dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  -- ft = { "typescript", "typescriptreact", "javascript", "javascriptreact" },
  -- opts = {
  --   on_attach = function(client, bufnr)
  --     client.server_capabilities.documentFormattingProvider = false
  --     client.server_capabilities.documentRangeFormattingProvider = false
  --   end,
  --   handlers = {
  --     ["textDocument/definition"] = function(err, result, ctx, config)
  --       if not result or vim.tbl_isempty(result) then
  --         return
  --       end
  --       local location = vim.islist(result) and result[1] or result
  --       vim.lsp.util.show_document(location.uri or location.targetUri, {
  --         range = location.range or location.targetRange,
  --         focus = true,
  --       })
  --     end,
  --   },
  --   settings = {
  --     separate_diagnostic_server = true,
  --     publish_diagnostic_on = "insert_leave",
  --     expose_as_code_action = {},
  --     tsserver_path = nil,
  --     tsserver_plugins = {},
  --     tsserver_max_memory = "auto",
  --     tsserver_format_options = {},
  --     tsserver_file_preferences = {},
  --     tsserver_locale = "en",
  --     complete_function_calls = false,
  --     include_completions_with_insert_text = true,
  --     code_lens = "off",
  --     disable_member_code_lens = true,
  --     jsx_close_tag = {
  --       enable = false,
  --       filetypes = { "javascriptreact", "typescriptreact" },
  --     },
  --   },
  -- },
}
